[[ghost_c]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ad716ecea3206b2f04ac0d757513d39fa62a9b1"
julia_version = "1.13.1"
libgfortran_version = "5.0.0"
os = "macos"

    [[ghost_c.download]]
    sha256 = "0a1c836833a616dcbbfcdec4289d8f683554d40c44eb7a46def9e9e85928b722"
    url = "https://github.com/JuliaConstraints/GHOST_jll.jl/releases/download/ghost-cabi-20261007-r2/ghost-macos-15.tar.gz"
[[ghost_c]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51e933ace221e929c769cc2dcab30224bac7d263"
julia_version = "1.13.1"
libgfortran_version = "5.0.0"
os = "macos"

    [[ghost_c.download]]
    sha256 = "26d9553e570b70d2d96b51df4ab35d5753a92291da9976a860a3ca8ebccf5979"
    url = "https://github.com/JuliaConstraints/GHOST_jll.jl/releases/download/ghost-cabi-20261007-r2/ghost-macos-15-intel.tar.gz"
[[ghost_c]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74dbb8a57bef486956d7c309611a37e1fa3e54c5"
julia_version = "1.13.1"
libc = "glibc"
libgfortran_version = "5.0.0"
libstdcxx_version = "3.4.30"
os = "linux"

    [[ghost_c.download]]
    sha256 = "df4553a4178edcce30d39fdb329d6f5332e7fb1e1783014e6dbd8f79cb0b90c5"
    url = "https://github.com/JuliaConstraints/GHOST_jll.jl/releases/download/ghost-cabi-20261007-r2/ghost-ubuntu-22.04.tar.gz"
[[ghost_c]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "da93c9cc9ebe0aaf8a3c4907eef672083d967d18"
julia_version = "1.13.1"
libc = "glibc"
libgfortran_version = "5.0.0"
libstdcxx_version = "3.4.30"
os = "linux"

    [[ghost_c.download]]
    sha256 = "2ed57b81fcbd52145c2ed43a059d3ee45dc576fc51ef86472cd0cf0aa1bde34b"
    url = "https://github.com/JuliaConstraints/GHOST_jll.jl/releases/download/ghost-cabi-20261007-r2/ghost-ubuntu-24.04-arm.tar.gz"
[[ghost_c]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2717b01977d61c84ab421c633873b1556f97b005"
julia_version = "1.13.1"
libgfortran_version = "5.0.0"
os = "windows"

    [[ghost_c.download]]
    sha256 = "5720d4db76be29ed5b526ce133b2368621071c9524d7a82cc39ecc330e452d86"
    url = "https://github.com/JuliaConstraints/GHOST_jll.jl/releases/download/ghost-cabi-20261007-r2/ghost-windows-2022.tar.gz"
